version: '3'
services:
    web:
        image: jameerbasha/flaskapp:2.0.0
        restart: always
        ports:
          - 8000:8000

    nginx:
        build: ./nginx
        restart: always
        links:
          - web:web
        depends_on:
          - web
        ports:
          - '80:80'
